# Generated by Django 4.1.7 on 2023-03-27 12:35

from django.db import migrations

def create_data(apps, schema_editor):
    art = apps.get_model("ecom","Article")
    art(name="art1", price=100).save()

class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),

    ]
