# Generated by Django 4.1.7 on 2023-06-02 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_category_promotion_user_client_produit_images_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.AddField(
            model_name='client',
            name='firstname',
            field=models.CharField(max_length=50, null=True, verbose_name='firstname'),
        ),
        migrations.AddField(
            model_name='order',
            name='dateorder',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='psw',
            field=models.CharField(max_length=60, verbose_name='psw'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=15, verbose_name='username'),
        ),
    ]
