# Generated by Django 4.1.7 on 2023-06-04 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecom", "0004_remove_images_image_client_firstname_order_dateorder_and_more"),
    ]

    operations = []
