# Generated by Django 4.1.7 on 2023-06-05 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecom", "0005_ecom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produit",
            name="promotionref",
        ),
    ]
