# Generated by Django 4.1.7 on 2023-06-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecom", "0006_remove_produit_promotionref"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dummy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test", models.CharField(max_length=80)),
            ],
        ),
    ]
