# Generated by Django 4.1.7 on 2023-06-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecom", "0007_dummy"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="description",
            field=models.CharField(default="description", max_length=440),
        ),
    ]
