# Generated by Django 4.1.7 on 2023-06-05 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecom", "0008_produit_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Dummy",
        ),
    ]
