# Generated by Django 4.1.7 on 2023-06-05 14:50

from django.db import migrations, models

# prod = apps.get_model("ecom", "Produit")
# img = apps.get_model("ecom", "Images")
# for product in products:
#     print(product["description"])
#     for image in product["images"]:
#         img.objects.create(
#             images=image,
#             prdRef=prod.objects.get(
#                 title=product["title"],
#                 price=product["price"],
#                 description=product["description"],
#                 categoryp=cat.objects.get(category=product["category"]),
#                 ratingt=product["rating"],
#                 stock=product["stock"],
#                 thumbnail=product["thumbnail"],
#             ),
#         ).save()
# prod.objects.create(
# title=product["title"],
# price=product["price"],
# description=product["description"],
# categoryp=cat.objects.get(category=product["category"]),
# ratingt=product["rating"],
# stock=product["stock"],
# thumbnail=product["thumbnail"],
# ).save()


class Migration(migrations.Migration):
    dependencies = [
        ("ecom", "0009_delete_dummy"),
    ]

    operations = [
        # migrations.CreateModel(
        #     name="Dummy",
        #     fields=[
        #         (
        #             "id",
        #             models.BigAutoField(
        #                 auto_created=True,
        #                 primary_key=True,
        #                 serialize=False,
        #                 verbose_name="ID",
        #             ),
        #         ),
        #         ("test", models.CharField(max_length=80)),
        #     ],
        # ),
    ]
