# Generated by Django 4.1.7 on 2023-06-05 15:03

from django.db import migrations, models

# products = requests.get("https://dummyjson.com/products").json()["products"]


class Migration(migrations.Migration):
    dependencies = [
        ("ecom", "0010_dummy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="Telephone",
            field=models.CharField(max_length=20, null=True, verbose_name="Telephone"),
        ),
    ]
