# Generated by Django 4.1.7 on 2023-06-05 15:05

from django.db import migrations, models


import requests


def create_data(apps, schema_editor):
    # categories = requests.get("https://dummyjson.com/products/categories").json()
    # cat = apps.get_model("ecom", "Category")
    # # for category in categories:
    # #     print(category)
    # #     cat.objects.create(category=category).save()
    data = requests.get("https://dummyjson.com/users").json()["users"]
    client = apps.get_model("ecom", "client")

    for user in data:
        client.objects.create(
            username=user["username"],
            psw=user["password"],
            name=user["firstName"],
            firstname=user["lastName"],
            # remvoe the +33
            Telephone=user["phone"].replace("+", ""),
            Mail=user["email"],
        ).save()


class Migration(migrations.Migration):
    dependencies = [
        ("ecom", "0011_alter_client_telephone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dummy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test", models.CharField(max_length=80)),
            ],
        ),
        migrations.RunPython(create_data),
    ]
